PALSDatabase/urls.py
# urls.py - wfhb_log_app

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'wfhb_log.views.home', name='home'),
	# url(r'^wfhb_log/', include('wfhb_log.foo.urls')),

	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
	
	# this is where we put our loginPortal app
	url(r'^login/', include('loginPortal.urls')),

	url(r'^$', include('loginPortal.urls')), # allows url to directly find login page without having to specify login/ as postfix
)

loginPortal/urls.py
# urls.py - loginPortal

# import some stuff we will need from django and our own views pages
from django.conf.urls import patterns, url
from loginPortal import views

urlpatterns = patterns( ' ', 
	# ex /loginPortal/
	url(r'^$', views.my_login, name="login"),
                       
    # this is the medical form
	url(r'^medical/', views.medical, name="medical"),

	# this is the regi form
	url(r'^regi/', views.regi, name="regi"),
	
	# this is the authentication buffer
	url(r'^auth/', views.auth_buff, name="auth_buff"),
	
	# /login/3 - this is for the clock in page
	url(r'^clock_in/$', views.clock_in, name="clock_in"),
	
	url(r'^log/', views.log_buff, name="log_buff"),
	
	#clock-out
	url(r'^clock_out/$', views.clock_out, name="clock_out"),
	
	url(r'^out/', views.out_buff, name="out_buff"),
	
	#missedpunch
	url(r'^missedpunch/$', views.missedpunch, name="missedpunch"),
	
	# time_stamp - this page is for volunteers who need to record their hours
	# NOTE: this is not the clock-in / clock-out page. They just enter total hours worked
	url(r'^time_stamp/$', views.time_stamp, name="time_stamp"),
	
	# this is the buffer for the time stamp that will write to the database to figure shit out
	url(r'^time_stamp_buff/$', views.time_stamp_buff, name="time_stamp_buff"),
	
	# this is the logout buffer, it will bring you back to the login page after loggin a user out
	url(r'^logout/', views.my_logout, name="logout"),
	
	#temporary loged page
	url(r'^loged/', views.loged, name="loged"),

	#volunteer page
	url(r'^volunteer/', views.volunteer, name="volunteer"),

	# volunteer detail page
	url(r'^detail/', views.detail, name="detail"),

	#link to the volunteer level acess.
	url(r'^volunteer_detail/', views.volunteer_detail, name="volunteer_detail"),
)

loginPortal/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.core.validators import RegexValidator
from django import forms

# Create your models here.
class UserManager(BaseUserManager):
	# creates a normal user, a 'volunteer' if I may
	def create_user(self, email, first_name, last_name, address, phone_number, date_of_birth, password):
		now  = timezone.now()
		
		# check if they passed an email
		if not email:
			raise ValueError('The given email is not good')
		email = self.normalize_email(email)
		
		# create the user
		user = self.model(
			email = email,
			first_name = first_name,
			last_name = last_name,
			address = address,
			phone_number = phone_number,
			date_of_birth = date_of_birth,
			start_date = now,
			is_active = False,
			is_staff = False,
			is_superuser = False
		)

		# save the user
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, first_name, last_name, address, phone_number, date_of_birth, password):
		now  = timezone.now()
		
		# check if they passed an email
		if not email:
			raise ValueError('The given email is not good')
		email = self.normalize_email(email)
		
		# create the user
		user = self.model(
			email = email,
			first_name = first_name,
			last_name = last_name,
			address = address,
			phone_number = phone_number,
			date_of_birth = date_of_birth,
			start_date = now,
			is_active = True,
			is_staff = True,
			is_superuser = True
		)
		
		# save the new user
		user.set_password(password)
		user.save(using=self._db)
		return user

# this allows us to define a new user based on the volunteer class 
# this means that we can also create an authentication process that
# uses our Volunteer objects
class User(AbstractBaseUser, PermissionsMixin):
	# there is an implicit primary key that is declared - its just an integer 
	# so if you look at this table there will be a primary key called 'id' that 
	# will be an integer. However, email is still unique and will be used for authentication
	email = models.EmailField(max_length=75, unique=True, db_index=True)
	first_name = models.CharField(max_length=25)
	last_name = models.CharField(max_length=25)
	address = models.CharField(max_length=200)
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
	phone_number = models.CharField(validators=[phone_regex], blank=True, max_length=15)
	date_of_birth = models.DateField('Birthday')
	start_date = models.DateField('start date')
	is_active = models.BooleanField(default=False)
	is_staff = models.BooleanField(default = False)
	
	
	# make sure that the username field points to the email address
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = [
		'first_name', 'last_name', 'address', 'phone_number', 'date_of_birth']
	
	objects = UserManager()
	
	def get_full_name(self):
		return self.first_name + " " + self.last_name
		
	def get_short_name(self):
		return self.email
		
	def email_user(self, subject, message, from_email=None):
		send_mail(subject, message, from_email, [self.email])
	
	def __unicode__(self):
		return self.email

#==================================================
#ADMIN
class Volunteer(User):
	class Meta:
		verbose_name = 'Volunteer user'

#==================================================
class Limited(Volunteer):
	class Meta:
		verbose_name = 'Limited User'
#==================================================
class Admin(Limited):
	class Meta:
		verbose_name = 'Admin User'

#==================================================
class Program(models.Model):
	program_name=models.CharField(max_length=50)
	program_start_date=models.DateField()
	program_end_date=models.DateField()
	program_type_choices = (
		('TH', 'Therapeutic'), 
		('RC', 'Recreational'), 
		('VT', 'Veteran'),
		('SP', 'Special'),
	)
	program_type=models.CharField(max_length=50, choices=program_type_choices)

class Vet(models.Model):
	vet_first_name=models.CharField(max_length=50)
	vet_last_name=models.CharField(max_length=50)
	vet_address_street=models.CharField(max_length=50)
	vet_address_suite=models.IntegerField(max_length=10)
	vet_address_city=models.CharField(max_length=50)
	vet_address_state=models.CharField(max_length=2)
	vet_address_zip=models.IntegerField(max_length=10)
	vet_phone=models.IntegerField(max_length=10)
	vet_email=models.CharField(max_length=50)

#=======Person Table======
yes_no=(
		('Y', 'Yes'),
		('N', 'NO'),
	)
class Person(models.Model):
	person_salutation_choices=(
		('Mr.', 'Mr.'),
		('Mrs.', 'Mrs.'),
		('Ms.', 'Ms.'),
		('Dr.', 'Dr.'),
	)
	person_salutation=models.CharField(max_length=4, choices=person_salutation_choices)
	person_first_name=models.CharField(max_length=50)
	person_middle_name=models.CharField(max_length=50)
	person_last_name=models.CharField(max_length=50)
	person_address_street=models.CharField(max_length=50)
	person_address_suite=models.IntegerField(max_length=10)
	person_address_city=models.CharField(max_length=50)
	person_address_state=models.CharField(max_length=2)
	person_address_zip=models.IntegerField(max_length=10)
	person_address_county=models.CharField(max_length=25)
	person_live_within_bloom=models.CharField(max_length=1, choices=yes_no)
	person_home_phone=models.IntegerField(max_length=10)
	person_cell_phone=models.IntegerField(max_length=10)
	person_work_phone=models.IntegerField(max_length=10)
	person_email=models.CharField(max_length=50)
	person_second_email=models.CharField(max_length=50)
	person_communication_preference_choices=(
		('Phone','Phone'), 
		('Email', 'Email'), 
		('Text', 'Text'),
	)
	person_communication_preference=models.CharField(max_length=10, choices=person_communication_preference_choices)
	person_dob=models.DateField()
	person_entered_in_donor_database=models.CharField(max_length=1, choices=yes_no)
	person_community_member=models.CharField(max_length=1, choices=yes_no)
	person_participation_start_date=models.DateField()
	person_participation_end_date=models.DateField()
	person_reason_for_leaving_choices=(
		('Moving', 'Moving'), 
		('Financial', 'Financial'), 
		('Medical', 'Medical'), 
		('Graduated', 'Graduated'), 
		('CSH', 'Completed Service Hours'), 
		('Other', 'Other'),
	)
	person_reason_for_leaving=models.CharField(max_length=20, choices=person_reason_for_leaving_choices)
	#// ^ needs to be checkboxes
	person_consent_medical_release_completed=models.CharField(max_length=1, choices=yes_no)
	person_consent_medical_release_completion_date=models.DateField()
	person_photo_consent_completed=models.CharField(max_length=1, choices=yes_no)
	person_photo_consent_completion_date=models.DateField()
	person_liability_consent_completed=models.CharField(max_length=1, choices=yes_no)
	person_liability_consent_completion_date=models.DateField()
	person_health_history_completed=models.CharField(max_length=1, choices=yes_no)
	person_health_history_completion_date=models.DateField()
	person_note=models.CharField(max_length=500)

#Client Table
	
class Client(Person):
	client_doctor_form_completion_date=models.DateField()
	client_diagnosis_name_choices=(
		('Amputation', 'Amputation'), 
		('Anxiety Dis', 'Anxiety disorder'), 
		('Arthritis/Rheumatoid', 'Arthritis/Rheumatoid Arthritis'), 
		('ADHD', 'Attention Deficit Hyperactivity Disorder'), 
		('Autism', 'autism spectrum (including Aspergers)'),
		('Bipolar', 'Bipolar disorder'), 
		('Borderline','Borderline personality'), 
		('Brain Injury', 'Brain injury'), 
		('CP', 'Cerebral palsy'), 
		('Deression', 'Depression'), 
		('Down Syndrome', 'Down syndrome'), 
		('Dyscalculia', 'Dyscalculia'), 
		('Dyslexia', 'Dyslexia'), 
		('Epilepsy', 'Epilepsy'), 
		('FAS', 'Fetal alcohol syndrome'), 
		('Fibromyalgia', 'Fibromyalgia'), 
		('Fragile X', 'Fragile X syndrome'), 
		('Hearing Impairment', 'Hearing impairment'), 
		('Hypotonia/Hypertonia', 'Hypotonia/Hypertonia'), 
		('Intellectual Disability', 'Intellectual Disability'), 
		('Muscular dystrophy', 'Muscular dystrophy'), 
		('OCD', 'Obsessive compulsive disorder'), 
		('PDD', 'Pervasive development disorder'), 
		('Schizophrenia', 'Schizophrenia'), 
		('Sensory Processing Disorder', 'Sensory processing disorder'), 
		('Speech Delay', 'Speech delay'), 
		('Spina Bifida', 'Spina bifida'), 
		('Visual Impairment', 'Visual impairment'), 
		('Other', 'Other'), 
		('Tramatic Brain Injury', 'Traumatic brain injury'), 
		('PTSD', 'Post traumatic stress disorder'),
	)
	#// ^ needs to be a checkboxes because client can have multiple disabilities; "Other" selection needs to have a text box with it
	client_diagnosis_name=models.CharField(max_length=100, choices=client_diagnosis_name_choices)
	client_disability_category_choices=(
		('Physical', 'Physical'), 
		('Cognitive/Neurological', 'Cognitive/Neurological'), 
		('Social', 'Social'), 
		('Emotional', 'Emotional'), 
		('Developmental', 'Developmental'),
	)
	client_disability_category=models.CharField(max_length=100, choices=client_disability_category_choices)
	#// ^ again, checkboxes because they can be multiple
	client_other_therapies_choices=(
		('PT', 'PT'), 
		('OT', 'OT'), 
		('Speech', 'Speech'), 
		('Other', 'Other'),
	)
	client_other_therapies=models.CharField(max_length=50, choices=client_other_therapies_choices)
	#// checkboxes, also 'Other' needs to have a Text box
	client_scholarship_name=models.CharField(max_length=50)
	client_scholarship_quarter_year=models.CharField(max_length=50)
	client_scholarship_application_date=models.DateField()
	client_scholarship_acceptance_date=models.DateField()
	client_scholarship_disbursement_date=models.DateField()
	client_service_hours_for_quarter_completed=models.CharField(max_length=1)
	client_service_hours_completion_date=models.DateField()
	client_income_bracket_choices=()
	#// ^ don't know what these choices should be; SHOULD BE OPTIONAL

loginPortal/templates/loginPortal/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

{% load staticfiles %}

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'loginPortal/style.css' %}" rel="stylesheet" type="text/css" />
    </head>

    <body>
    	<div class = 'wrapper'>
    		<nav>
            	<ul>
               		<li><a href=''>HOME</a></li>
                    <li><a href=''>ABOUT US</a></li>
                    <li><a href=''>OUR SERVICES</a></li>
                    <li><a href=''>HOW TO HELP</a></li>
                    <li><a href=''>NEWS & EVENTS</a></li>
                    <li><a href=''>CAPITAL CAMPAIGN</a></li>
                    <li><a href=''>CONTACT</a></li>
                    <li style="border-right: 1px white solid;"><a href=''><img src="{% static "loginPortal/images/cart.png" %}" width='38' height='30' alt="Checkout"/></a></li>
                </ul>
            </nav>
            <div class='triangle-l'></div>
            <div class='triangle-r'></div>
    	    <div id="content">
        	   <div class='header'>
                    <div class='img'>
                        <img src="{% static "loginPortal/images/PALS_MSCL_FINAL-300x184.jpg" %}" width='300' height='184' alt="Pals: People and Animal Learning Services. Making Strides, Changing Lives."/>
                    </div>
                    <div class='tbl'>
                        <table class='right'>
                            <tr>
                                <td class='participate'><a href=''><img src="{% static 'loginPortal/images/blank.png' %}"></a></td>
                                <td class='donate'><a href=''><img src="{% static 'loginPortal/images/blank.png' %}"></a></td>
                                <td class='volunteer'><a href=''><img src="{% static 'loginPortal/images/blank.png' %}"></a></td>
                            </tr>
                            <tr>
                            	<td> <a href=''>PARTICIPATE</a></td>
                                <td><a href=''>DONATE</a></td>
                                <td><a href=''>VOLUNTEER</a></td>
                            </tr>
                        </table>
                    </div>
                </div>
                {% block page %}
                {% endblock %}
                {% block buttons %}
                {% endblock %}
            </div>
         </div>
    </body>
</html>

loginPortal/templates/loginPortal/base_loged.html
<!DOCTYPE html>

{% load staticfiles %}

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'loginPortal/style.css' %}" rel="stylesheet" type="text/css" />
        <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    </head>

    <body>
    	<div class = 'wrapper'>
            <nav>
               	<ul>
               		<li><a href=''>HOME</a></li>
                    <li><a href=''>ABOUT US</a></li>
                    <li><a href=''>OUR SERVICES</a></li>
                    <li><a href=''>HOW TO HELP</a></li>
                    <li><a href=''>NEWS & EVENTS</a></li>
                    <li><a href=''>CAPITAL CAMPAIGN</a></li>
                    <li><a href=''>CONTACT</a></li>
                    <li style="border-right: 1px white solid;"><a href=''><img src="{% static "loginPortal/images/cart.png" %}" width='38' height='30' alt="Checkout"/></a></li>
                </ul>
            </nav>
            <div class='triangle-l'></div>
            <div class='triangle-r'></div>
    	    <div id="content">
        	   <div class='header'>
                    <div class='img'>
                        <img src='{% static "loginPortal/images/PALS_MSCL_FINAL-300x184.jpg" %}' width='300' height='184' alt="Pals: People and Animal Learning Services. Making Strides, Changing Lives."/>
                    </div>
                    <div class='tbl'>
                        <table class='right'>
                            <tr>
                                <td class='participate'><a href=''><img src="{% static 'loginPortal/images/blank.png' %}"></a></td>
                                <td class='donate'><a href=''><img src="{% static 'loginPortal/images/blank.png' %}"></a></td>
                                <td class='volunteer'><a href=''><img src="{% static 'loginPortal/images/blank.png' %}"></a></td>
                            </tr>
                            <tr>
                            	<td><a href=''>PARTICIPATE</a></td>
                                <td><a href=''>DONATE</a></td>
                                <td><a href=''>VOLUNTEER</a></td>
                            </tr>
                        </table>
                    </div>
                </div>
               <div class='header2'>
                    <div id="nav2">
                        <ul class="nav2">
                            <li><a href="">VOLUNTEERS</a>
                                <ul>
                                    <li><a href="/login/volunteer/">Genereal Information</a></li>
                                    <li><a href="/login/medical/">Medical Information</a></li>
                                    <li><a href="">Program Participation</a></li>
                                    <li><a href="/login/regi/">Registratio Form</a></li>
                                </ul>
                            </li>
                            <li><a href=''>CLIENTS</a></li>
                            <li><a href=''>STAFF</a></li>
                            <li><a href=''>HORSES</a></li>
                            <li><a href=''>PROGRAMS</a></li>
                            <li><a href=''>GOALS</a></li>
                            <li><a href=''>SESSIONS</a></li>
                            <li style="border-right: 1px white solid;"><a href="/login/logout/">LOGOUT</a></li>
                        </ul>
                    </div>
                    <div class='triangle-l2'></div>
                    <div class='triangle-r2'></div>
                </div>
                {% block page %}
                {% endblock %}
                {% block buttons %}
                {% endblock %}
            </div>
         </div>
    </body>
</html>

loginPortal/templates/loginPortal/base_volunteer.html
<!DOCTYPE html>

{% load staticfiles %}

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'loginPortal/style.css' %}" rel="stylesheet" type="text/css" />
        <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    </head>

    <body>
    	<div class = 'wrapper'>
            <nav>
               	<ul>
               		<li><a href=''>HOME</a></li>
                    <li><a href=''>ABOUT US</a></li>
                    <li><a href=''>OUR SERVICES</a></li>
                    <li><a href=''>HOW TO HELP</a></li>
                    <li><a href=''>NEWS & EVENTS</a></li>
                    <li><a href=''>CAPITAL CAMPAIGN</a></li>
                    <li><a href=''>CONTACT</a></li>
                    <li style="border-right: 1px white solid;"><a href=''><img src="{% static "loginPortal/images/cart.png" %}" width='38' height='30' alt="Checkout"/></a></li>
                </ul>
            </nav>
            <div class='triangle-l'></div>
            <div class='triangle-r'></div>
    	    <div id="content">
        	   <div class='header'>
                    <div class='img'>
                        <img src='{% static "loginPortal/images/PALS_MSCL_FINAL-300x184.jpg" %}' width='300' height='184' alt="Pals: People and Animal Learning Services. Making Strides, Changing Lives."/>
                    </div>
                    <div class='tbl'>
                        <table class='right'>
                            <tr>
                                <td class='participate'><a href=''><img src="{% static 'loginPortal/images/blank.png' %}"></a></td>
                                <td class='donate'><a href=''><img src="{% static 'loginPortal/images/blank.png' %}"></a></td>
                                <td class='volunteer'><a href=''><img src="{% static 'loginPortal/images/blank.png' %}"></a></td>
                            </tr>
                            <tr>
                            	<td><a href=''>PARTICIPATE</a></td>
                                <td><a href=''>DONATE</a></td>
                                <td><a href=''>VOLUNTEER</a></td>
                            </tr>
                        </table>
                    </div>
                </div>
               <div class='header2'>
                    <div id="nav2">
                        <ul class="nav2">
                            <li><a href="">VOLUNTEERS</a>
                                <ul>
                                    <li><a href="/login/volunteer_detail/">Genereal Information</a></li>
                                    <li><a href="">Medical Information</a></li>
                                    <li><a href="">Program Participation</a></li>
                                    <li><a href="">Program Outcomes</a></li>
                                </ul>
                            </li>/
                            <li><a href='/login/clock_in'>CLOCK IN</a></li>
                            <li><a href='/login/clock_out'>CLOCK OUT</a></li>
                            <li><a href='/login/time_stamp'>TIME STAMP</a></li>
                            <li style="border-right: 1px white solid;"><a href="/login/logout/">LOGOUT</a></li>
                        </ul>
                    </div>
                    <div class='triangle-l2'></div>
                    <div class='triangle-r2'></div>
                </div>
                {% block page %}
                {% endblock %}
                {% block buttons %}
                {% endblock %}
            </div>
         </div>
    </body>
</html>

loginPortal/templates/loginPortal/clock_in.html
{% extends "loginPortal/base_loged.html" %}

{% block title %} Clock-In {% endblock %}

{% block page %}
	<span style="padding-right: 1%;">
	 WELCOME, {{ user }}
	</span>	
	<br />
		
	<span style="text-align: left;">
	Total Hours: {{ overall_hours }}
	<br />
	
	Total Quarterly Hours: {{ quarterly_hours }}
	</span>
	
	
	<span id="logoutbutton">
	<a href="/login/logout/">LOGOUT</a>
	</span>
	
	<br />
	
	
	<br /><br />
{% endblock %}	
	
{% block buttons %}						
<form action="/login/log/" method="POST" enctype="multipart/form-data" >{% csrf_token %}			
	<center><input type="submit" id="submitbutton" value="CLOCK-IN">
	
	<a id="submitbutton" href="/login/missedpunch/">
        				MISSED PUNCH
						</a>
</form>

 <br />
             
						

{% endblock %}	

loginPortal/templates/loginPortal/clock_out.html
{% extends "loginPortal/base_loged.html" %}
{% block title %} Clock-Out {% endblock %}
<script>
	var toggle = function() {
		var mydiv = document.getElementById('hourinfo');
		if (mydiv.style.display === 'block')
			mydiv.style.display = 'none';
		else
			mydiv.style.display = 'block'
	}
</script>

{% block page %}
	<span style="padding-right: 1%;">
	 WELCOME, {{ user }}
	</span>	
	<br />
		
	<span style="text-align: left;">
	Total Hours: {{ overall_hours }}
	<br />
	
	Total Quarterly Hours: {{ quarterly_hours }}
	</span>
	
	
	<span id="logoutbutton">
	<a href="/login/logout/">LOGOUT</a>
	</span>
	
	<br />
	
	
	<br /><br />
{% endblock %}	
	
{% block buttons %}
<form action="/login/out/" method="POST" enctype="multipart/form-data" >{% csrf_token %}
	<center><input type="submit" id="submitbutton" value="CLOCK-OUT" onclick="toggle();">
</form>
<br />
             
        			<a id="submitbutton" href="/login/missedpunch/">
        			MISSED PUNCH
					</a>
					
					<div id="hourinfo">
					<dl>
					<dd>
					Date ___ Hours ___
					</dd>
					</dl>
					</div>
					
{% endblock %}	

loginPortal/templates/loginPortal/loged.html
{% extends "loginPortal/base.html" %}
{% block title %} Loged {% endblock %}
{% block page %}
    
    <span id="logoutbutton">
    <a href="/login/logout/">LOGOUT</a>
    </span>
    
    <br />
    <span style="float: right; padding-right: 1%;">
     WELCOME, {{ user_name }} - Email: {{ user_email }}
    </span> 
    
    <br /><br />
{% endblock %} 

loginPortal/templates/loginPortal/login.html
{% extends "loginPortal/base.html" %}
{% block title %}Login Portal{% endblock %}

{% block page %}
<div id="loginbox"> 
    <form id="login" action="/login/auth/" method="post" autocomplete="off">{% csrf_token %}
  
        <h3>PALS Therapy login</h3>
            
        <br /><br />
                  
        <label> Email: </label> <input type="text" name="email" class="login"/>
                        
        <br /><br />

        <label>Password: </label> <input type="password" name="password" class="login"/>
                        
        <br /><br /><br />
                        
        <center><input type="submit" value="Login" class = "button"></center>
                    
    </form>
                
</div>
{% endblock %}

loginPortal/templates/loginPortal/regiform.html
{% extends "loginPortal/base_loged.html" %}
{% block title %} Registration Form {% endblock %}


{% block page %} 
<h1>Registration Form</h1>
<!--<img style="position: absolute;
    top: 0px;
    right: 0px;" src="/static/loginPortal/images/wfhb.gif" width="10%" height="10%"/>
<br/> -->
<hr style="border-top: dotted 1px;" />
<div id="form">
	
	<form action="/login/regi/" method="POST">{% csrf_token %}
		
		<div class="form_registration">
			{{ form.first_name.errors }}
			<label for="id_first_name">First Name: </label>
			{{ form.first_name }}
		</div>
		<div class="form_registration">
			{{ form.last_name.errors }}
			<label for="id_last_name">Last Name: </label>
			{{ form.last_name }}
		</div>		
		<div class="form_registration">
			{{ form.email.errors }}
			<label for="id_email">Email: </label>
			{{ form.email }}
		</div>
		<div class="form_registration">
			{{ form.password.errors }}
			<label for="id_contact_first_name">Password: </label>
			{{ form.password }}
		</div>
		<div class="form_registration">
			{{ form.address.errors }}
			<label for="id_address">Address: </label>
			{{ form.address }}
		</div>
		<div class="form_registration">
			{{ form.phone_number.errors }}
			<label for="id_phone_number">Phone Number: </label>
			{{ form.phone_number }}
		</div>
		<div class="form_registration">
			{{ form.date_of_birth.errors }}
			<label for="date_of_birth">Birthday: </label>
			{{ form.date_of_birth }}
		</div>
		<div class="form_registration">
			{{ form.start_date.errors }}
			<label for="id_start_date">Start Date: </label>
			{{ form.start_date }}
		</div>
		<div class="form_registration">
			{{ form.contact_first_name.errors }}
			<label for="id_contact_first_name">Contact First Name: </label>
			{{ form.contact_first_name }}
		</div>
		<div class="form_registration">
			{{ form.contact_last_name.errors }}
			<label for="id_contact_last_name">Contact Last Name: </label>
			{{ form.contact_last_name }}
		</div>
		<div class="form_registration">
			{{ form.contact_phone_number.errors }}
			<label for="id_contact_first_name">Contact Phone Number: </label>
			{{ form.contact_phone_number }}
		</div>
		<div class="form_registration">
			{{ form.relation_to_contact.errors }}
			<label for="id_relation_to_contact">Contact Relation: </label>
			{{ form.relation_to_contact }}
		</div>
		
		
		

		<input id="regi_submit" type="submit" value="Submit" />
	</form>
</div>
{% endblock %}